from sqlalchemy import Column, Integer, String, Float, Boolean, Date, Text, JSON, DateTime

from app.models.base import Base



#胸部肿瘤科肺康复患者调查表
class RehaPatient(Base):
    __tablename__ = 'rehaPatient'
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(20), comment='姓名')
    research_center_id = Column(Integer, comment='研究中心ID')
    idNumber = Column(String(18), comment='身份证号')
    hosNum = Column(String(20), comment='住院号')
    date = Column(Date, comment='填表日期')
    sex = Column(Boolean, comment='性别')
    age = Column(Integer, comment='年龄')
    height = Column(Float, comment='身高')
    weight = Column(Float, comment='体重')
    education = Column(String(20), comment='文化程度')
    isMarry = Column(Boolean, comment='婚否')
    phoneNum = Column(String(20), comment='联系电话')
    residence = Column(Boolean, comment='居住地(0-城市、1-农村)')
    work = Column(Integer, comment='工作情况(2-无工作、1-有工作、3-退休)')
    income = Column(Integer, comment='年收入情况(1-3万元以下、2-3-5万元、3-5-10万元、4-10万元以上)')
    isLunSur = Column(Boolean, comment='填表前肺部有无手术')
    postTime = Column(Integer, comment='术后时长(1：1周、2：2-4周、3：1-3个月、4：3个月以上)')
    isChem = Column(Boolean, comment='是否进行放化疗')
    period = Column(Integer, comment='疗程(1：第1个、2：第2-4个、3：第5个以上、4：放化疗结束)')
    PET = Column(Float, comment='PET')
    PET_ = Column(Float, comment='PET%')
    FEV1 = Column(Float, comment=' FEV1')
    FEV1_ = Column(Float, comment=' FEV1%')
    FVC = Column(Float, comment=' FVC')
    FEV1_FVC = Column(Float, comment=' FEV1/FVC')
    MWD6 =  Column(Float, comment=' 6MWD')
    ECOG =  Column(Float, comment='  ECOG')
    physical = Column(Integer, comment='体力状态')
    diffBre = Column(Integer, comment='呼吸困难情况')
    one = Column(Integer, comment='one,数字代表选择题顺序')
    two = Column(Integer, comment='two,数字代表选择题顺序')
    three = Column(Integer, comment='three,数字代表选择题顺序')
    four = Column(Integer, comment='four,数字代表选择题顺序')
    five = Column(Integer, comment='five,数字代表选择题顺序')
    six = Column(Integer, comment='six,数字代表选择题顺序')
    seven = Column(Integer, comment='seven,数字代表选择题顺序')
    eight = Column(Integer, comment='eight,数字代表选择题顺序')
    nine = Column(Integer, comment='nine,数字代表选择题顺序')
    ten = Column(Integer, comment='ten,数字代表选择题顺序')
    eleven = Column(Integer, comment='eleven,数字代表选择题顺序')
    twelve = Column(Integer, comment='twelve,数字代表选择题顺序')
    thirteen = Column(Integer, comment='thirteen,数字代表选择题顺序')
    fourteen = Column(Integer, comment='fourteen,数字代表选择题顺序')
    fifteen = Column(Integer, comment='fifteen,数字代表选择题顺序')
    sixteen = Column(Integer, comment='sixteen,数字代表选择题顺序')
    seventeen = Column(Integer, comment='seventeen,数字代表选择题顺序')
    eighteen = Column(Integer, comment='eighteen,数字代表选择题顺序')
    nineteen = Column(Integer, comment='nineteen,数字代表选择题顺序')
    twenty = Column(Integer, comment='twenty,数字代表选择题顺序')
    twenty_one = Column(Integer, comment='twenty_one,数字代表选择题顺序')
    twenty_two = Column(Integer, comment='twenty_two,数字代表选择题顺序')
    twenty_three = Column(Integer, comment='twenty_three,数字代表选择题顺序')
    twenty_four = Column(Integer, comment='twenty_four,数字代表选择题顺序')
    twenty_five = Column(Integer, comment='twenty_five,数字代表选择题顺序')
    twenty_six = Column(Integer, comment='twenty_six,数字代表选择题顺序')
    twenty_seven = Column(Integer, comment='twenty_seven,数字代表选择题顺序')
    twenty_eight = Column(Integer, comment='twenty_eight,数字代表选择题顺序')
    twenty_nine = Column(Integer, comment='twenty_nine,数字代表选择题顺序')
    thirty = Column(Integer, comment='thirty,数字代表选择题顺序')
    thirty_one = Column(Integer, comment='thirty_one,数字代表选择题顺序')
    thirty_two = Column(Integer, comment='thirty_two,数字代表选择题顺序')
    thirty_three = Column(Integer, comment='thirty_three,数字代表选择题顺序')
    thirty_four = Column(Integer, comment='thirty_four,数字代表选择题顺序')
    thirty_five = Column(Integer, comment='thirty_five,数字代表选择题顺序')
    thirty_six = Column(Integer, comment='thirty_six,数字代表选择题顺序')
    thirty_seven = Column(Integer, comment='thirty_seven,数字代表选择题顺序')
    thirty_eight = Column(Integer, comment='thirty_eight,数字代表选择题顺序')
    thirty_nine = Column(Integer, comment='thirty_nine,数字代表选择题顺序')
    forty = Column(Integer, comment='forty,数字代表选择题顺序')
    forty_one = Column(Integer, comment='forty_one,数字代表选择题顺序')
    forty_two = Column(Integer, comment='forty_two,数字代表选择题顺序')
    forty_three = Column(Integer, comment='forty_three,数字代表选择题顺序')
    effect = Column(Integer, comment='43题选是，止疼作用')
    painArea = Column(String(50), comment='疼痛部位')
    musFre = Column(Integer, comment='听音乐的频率')
    doByMus = Column(String(30), comment='利用音乐做什么,多个以逗号分隔')
    breExe = Column(Integer, comment='呼吸操')
    breExeHelp = Column(String(40), comment='呼吸操对自己哪些方面有帮助,多个以逗号分隔')
    isBreExe = Column(Integer, comment='愿意做呼吸操')
    frequency = Column(Integer, comment='频率')
    breExeMet = Column(Integer, comment='形式做呼吸操')
    breExeEff = Column(String(30), comment='呼吸操对肺部术后有哪些可能疗效,多个以逗号分隔')